# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Podcasts', folder: 'pages', file: 'podcasts.html'}
- {name: 'Feature Stories', folder: 'pages', file: 'stories.html'}
- {name: 'Glossary', folder: 'pages', file: 'glossary.html'}
- {name: 'Team Bios', folder: 'pages', file: 'bios.html'}

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
