# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Podcasts', folder: 'pages', file: 'facts.html'}
- {name: 'Feature Story 1', folder: 'pages', file: 'resources.html'}
- {name: 'Feature Story 2', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Feature Story 3', folder: 'pages', file: ''}
- {name: 'Glossary', folder: 'pages', file: 'documentation.html'}
- {name: 'Team Bios', folder: 'pages', file: 'about.html'}
- {name: 'References', folder: 'pages', file: 'contact.html'}

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
